added b2c data structures, converters and tests
tabiszs/partyKLINest pull request #36
Opened 2022-04-10 22:21 UTC by jakubrymuza

2022-04-11 10:01 UTC, TortillaZHawaii requested changes
Ogółem to brakuje mi jeszcze sposobu użycia tego w endpointach. Na pewno da się to zrobić gotowymi paczkami, Microsoft stworzył oba produkty. Wydaje mi się, że będzie to coś z nazwą Identity, ale wymaga to researchu. Chodzi też o to by nie otwierać otwartych drzwi. Obecne rozwiązanie wymagało by abyśmy w każdym endpoincie prowadzili weryfikacje użytkowników poprzez sprawdzanie Tokenu z body, a to powinno być robione wspólnie dla każdego requestu przed wywołaniem endpointu. Na 100% Identity będzie miało do tego gotowy Middleware, który będzie wymagał jakiegoś małego setupu, między innymi napisania że pod /api/Cleaner/* powinien mieć tylko dostęp Admin i Cleaner.

2022-04-11 11:00 UTC, TortillaZHawaii commented
Warto [stąd](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-protected-web-api-overview "Docs Microsoft") zaczerpnąć inspiracji odnośnie Identity. Patrzyłem to tam jest jakiś przykładowy projekt, ale od 3 lat nie był ruszany, więc brałbym z samej dokumentacji rzeczy, tego tutorialu i na endpointach spojrzał na jakieś inne przykładowe appki lub eShopOnWeb. Problem z eShopOnWeb jest taki że on sam ma bazę podpiętą z użytkownikami i claimsami, a nie korzysta z AD B2C, ale reszta powinna być podobna.

2022-04-11 20:56 UTC, zh-qs requested changes

2022-04-11 20:56 UTC, zh-qs commented on backend/src/ApplicationCore/Entities/b2c/Claim.cs
> +        public Claim(string accountType, string city, string country, StringCollection email, string givenName, bool isBanned, string postalCode, string province, string streetAddress, string surname
Nazwy pól w claimie mogą być inne (zobacz DataClasses/MsalTokenClaims.ts na froncie)

2022-04-11 20:56 UTC, zh-qs commented on backend/src/ApplicationCore/Entities/b2c/Token.cs
> +            UserType = b2c.UserTypeConverter.StringToEnum(claim.AccountType);
Raczej nie ten konwerter, pole extension_AccountType w claimach przyjmuje wartości: Client: "0", Cleaner: "1", Admin: "2" (nie są to inty, tylko stringi)

2022-04-11 20:56 UTC, zh-qs commented on backend/src/ApplicationCore/Entities/b2c/UserTypeConverter.cs
> +                case "Organizer":
"Organizer" -> "Administrator"

2022-04-11 20:56 UTC, zh-qs commented on backend/src/ApplicationCore/Entities/b2c/UserTypeConverter.cs
> +        public static string EnumToString(UserType userType)
polecam https://weblogs.asp.net/stefansedich/enum-with-string-values-in-c

2022-04-11 20:56 UTC, zh-qs commented on backend/src/ApplicationCore/Entities/b2c/Token.cs
> +            UserType = b2c.UserTypeConverter.StringToEnum(claim.AccountType);
Ogólnie trochę głupio wyszło, ale właśnie w API są te ładne tekstowe wartości enuma (np. "Cleaner"), a Azure (przynajmniej przez Reacta) zwraca "0", "1" lub "2"

2022-04-19 17:53 UTC, jakubrymuza commented on backend/src/ApplicationCore/Entities/b2c/UserTypeConverter.cs
> +                case "Organizer":
W specyfikacji było "Organizer" w tych claimsach na Azure
![obraz](https://user-images.githubusercontent.com/94860838/164065603-f38cf645-265c-42de-abb9-3c75f868a1f4.png)

2022-04-20 06:55 UTC, zh-qs commented on backend/src/ApplicationCore/Entities/b2c/UserTypeConverter.cs
> +                case "Organizer":
Teraz jest Administrator
![obraz](https://user-images.githubusercontent.com/91987031/164168608-ed2a7074-666a-428f-a2d6-eacd2132ed4b.png)

2022-04-22 13:52 UTC, TortillaZHawaii requested changes
Nadal brakuje użycia tego w akcji. Celem tego taska jest umożliwienie autentykacji i autoryzacji użytkownika w endpointach na podstawie tokenów przekazywanych w requestach i pobieranie danych z tokenu do przetwarzania w logice biznesowej. Np w endpoincie /order/{id}/rate musimy znać kto wysyła zapytanie, czy rzeczywiście jest to osoba przypisana do tego orderu, i z której strony daje recenzję, tzn jako klient czy jako osoba sprzątająca. Obecnie nie widzę jak to byłoby możliwe.

2022-04-22 13:52 UTC, TortillaZHawaii commented on backend/src/Infrastructure/Identity/AppIdentityDbContext.cs
> +    public class AppIdentityDbContext : IdentityDbContext<ApplicationUser>
Dlaczego mamy oddzielny IdentityDbContext? Wydaje mi się, że nie potrzebujemy mieć drugiej bazy danych do Claimsów i Role, do tego miał służyć AD B2C.

2022-04-22 13:52 UTC, TortillaZHawaii commented on backend/src/Infrastructure/Migrations/PartyKlinerDbContextModelSnapshot.cs
> -                                .HasColumnType("text")
Lepiej character varying(10)

2022-04-23 16:46 UTC, jakubrymuza commented on backend/src/Infrastructure/Data/Identity/Claim.cs
> +            // TODO: multi-segment street name
Tu jest napisane tak, że dobrze będzie traktować jak ulica będzie jednoczłonowa i dałem todo na później

2022-04-23 16:47 UTC, jakubrymuza commented on backend/src/Infrastructure/Data/Identity/Claim.cs
> +        public string oid { get; }
Szymon coś pisał, że te nazwy powinny być takie jak w DataClasses/MsalTokenClaims.ts na froncie

2022-04-23 16:49 UTC, jakubrymuza commented on backend/src/Infrastructure/Migrations/PartyKlinerDbContextModelSnapshot.cs
> -                                .HasColumnType("text")
to chyba nie ja pisałem

2022-05-05 18:18 UTC, TortillaZHawaii commented
Przeniesione do https://github.com/tabiszs/partyKLINest/pull/57

2022-05-05 18:18 UTC, closed without merging