Feature/routing change
tabiszs/partyKLINest pull request #37
Opened 2022-04-11 18:04 UTC by zh-qs

2022-04-11 18:04 UTC, zh-qs commented
Poszedł porządny refactor, mogą być konflikty

2022-04-13 11:49 UTC, szymon-zygula requested changes

2022-04-13 11:49 UTC, szymon-zygula commented on frontend/src/Layouts.tsx
> +);
To trzebaby zamienić na odpowiednie ścieżki

2022-04-18 13:46 UTC, szymon-zygula approved these changes

2022-04-19 14:40 UTC, merged