Feature/cleaner facade
tabiszs/partyKLINest pull request #40
Opened 2022-04-13 13:50 UTC by tabiszs

2022-04-13 15:13 UTC, TortillaZHawaii requested changes
Wygląda oki, wymaga drobnych poprawek. Very hot testy jednostkowe 🔥🔥.
Jeszcze mam prośbę żebyś uruchomił Code Cleanup na całej solucji, żeby poprawić jakieś zbędne lub brakujące spacje, wcięcia i usunąć nie używane importy. Jak masz VS2022 to można to zrobić jak we flutterze przy ctrl+s https://devblogs.microsoft.com/visualstudio/bringing-code-cleanup-on-save-to-visual-studio-2022-17-1-preview-2/

2022-04-13 19:29 UTC, tabiszs commented on backend/src/ApplicationCore/Services/CleanerFacade.cs
> +            return await _orderRepository.ListAsync(spec);
GetCleanerInfo sprawdza czy cleanerId nie jest null. Czy to się jakoś automatycznie sprawdza przy wyszukiwaniu?

2022-04-13 19:38 UTC, tabiszs commented on backend/src/ApplicationCore/Services/CleanerFacade.cs
> +        private async Task<Order> GetOrderAsync(long orderId)
Właśnie się zastanawiałem.
Czy OrderFacade zajmuje się logiką biznesową tylko zamówień, a CleanerFacade zajmuje się logiką sprzątacza.
Czy może OrderFacade zajmuje tym co tyczy się zamówień niezależnie od biznesu.
Jak myślisz?

2022-04-13 19:41 UTC, tabiszs commented on backend/src/ApplicationCore/Services/CleanerFacade.cs
> +        public async Task AcceptRejectOrder(string cleanerId, Order sentOrder)
/orders/{id}*POST 
Przekazywane są całe struktury i trzeba wyłuskać co się powinno zmienić i w jakiej kolejności.

2022-04-13 19:43 UTC, tabiszs commented on backend/tests/UnitTests/ApplicationCore/Services/CleanerFacadeTests/AcceptRejectOrder.cs
> +        // reject [InlineData("localCleanerId22", OrderStatus.Active,     "localCleanerId22", OrderStatus.Active, null)]
Można by to usunąć ale myślę, że to trochę ułatwia połapać się w liczbie tych przypadków.
Na wszystkie możliwe przypadki zmiany statusu zamówienia cleaner może podjąć tylko dwie akcje: accept - test1, reject - test2. Pozostałe przypadki poszły do test3 i mają dawać wyjątek.

2022-04-13 19:44 UTC, tabiszs commented
Jak dodawać takie komentarze do konkretnych plików?

2022-04-14 14:50 UTC, TortillaZHawaii commented on backend/src/ApplicationCore/Services/CleanerFacade.cs
> +            return await _orderRepository.ListAsync(spec);
Aa rzeczywiście, słusznie.

2022-04-15 20:29 UTC, TortillaZHawaii commented on backend/src/ApplicationCore/Services/CleanerFacade.cs
> +        private async Task<Order> GetOrderAsync(long orderId)
Mi się wydaję, że granice są rozmyte i dobre ich określenie wymaga dużo doświadczenia. Ale w tym przypadku zostało to już zaimplementowane z testami w OrderFacade, więc imo warto już dodać prywatne pole ```private readonly OrderFacade _orderFacade```, pobrać je w konstruktorze i z niego korzystać.

2022-04-15 20:29 UTC, TortillaZHawaii commented on backend/src/ApplicationCore/Services/CleanerFacade.cs
> +        public async Task AcceptRejectOrder(string cleanerId, Order sentOrder)
Oki

2022-04-15 20:30 UTC, TortillaZHawaii commented on backend/tests/UnitTests/ApplicationCore/Services/CleanerFacadeTests/AcceptRejectOrder.cs
> +        // reject [InlineData("localCleanerId22", OrderStatus.Active,     "localCleanerId22", OrderStatus.Active, null)]
Oki

2022-04-19 07:53 UTC, tabiszs commented on backend/src/ApplicationCore/Services/CleanerFacade.cs
> +        private async Task<Order> GetOrderAsync(long orderId)
Uniezależniłem cleanerFacade od orderRepository. Myślę, że tak powinno być. Dzięki temu mamy większą niezależność.

2022-04-19 09:24 UTC, TortillaZHawaii requested changes
Należałoby jeszcze zrobić migracje na bazie danych, ponieważ Cleaner ma zmiany. Ale może poczekałbym z tym na Kubę, bo on też coś pozmieniał w Entities, a chciałbym uniknąć konfliktów.

2022-04-19 09:24 UTC, TortillaZHawaii commented on backend/src/ApplicationCore/Services/CleanerFacade.cs
> +        private async Task<Order> GetOrderAsync(long orderId)
GetOrderAsync tutaj jest do usunięcia już.

2022-04-19 09:24 UTC, TortillaZHawaii commented on backend/src/ApplicationCore/Services/CleanerFacade.cs
> +        private void CloseOrder(Order order)
Ja przerzuciłbym to do OrderFacade jako metodę publiczną.

2022-04-20 07:33 UTC, tabiszs commented on backend/src/ApplicationCore/Services/CleanerFacade.cs
> +        private async Task<Order> GetOrderAsync(long orderId)
To jest już metoda orderFacade, więc myślę, że tak zostanie.

2022-04-20 08:01 UTC, TortillaZHawaii approved these changes

2022-04-20 08:01 UTC, merged