complete cleaner controller and commision controller
tabiszs/partyKLINest pull request #62
Opened 2022-05-09 08:55 UTC by tabiszs

2022-05-10 13:47 UTC, TortillaZHawaii requested changes
Jeśli jest authorize to nie potrzebujemy już sprawdzania dodatkowego czy to jest client, czy admin itd. IsAdmin są potrzebne gdy akceptujemy dwie role w endpoincie i mamy dla nich różne akcje. Plus jeszcze nie trzeba konwertować samemu enumów ze switcha, to się robi automatycznie u nas.

2022-05-10 13:47 UTC, TortillaZHawaii commented on backend/src/WebApi/Controllers/CommissionController.cs
> +            if (User.IsAdmin())
Do czego jest to sprawdzenie czy User jest adminem? Do tego endpointu może wejść tylko admin, przez to że jest [Authorize(Policy = "AdminOnly")].

2022-05-10 20:26 UTC, tabiszs commented on backend/src/WebApi/Extensions/CleanerStatusExtention.cs
> +    public static class CleanerStatusExtention
Nie wiedziałem.

2022-05-10 20:37 UTC, tabiszs commented on backend/src/WebApi/Extensions/CleanerStatusExtention.cs
> +    public static class CleanerStatusExtention
A w drugą stronę też to działa? Json -> Cleaner Status

2022-05-12 18:34 UTC, TortillaZHawaii commented on backend/src/WebApi/Extensions/CleanerStatusExtention.cs
> +    public static class CleanerStatusExtention
tak, w obie strony

2022-05-12 18:41 UTC, TortillaZHawaii approved these changes
wyglada oki

2022-05-14 21:37 UTC, tabiszs commented
Dodałem dodawanie cleanerów. (bez testów)
Nie udało mi się poprawnie autoryzować klienta przez swaggera.

2022-05-15 17:45 UTC, zh-qs commented
jest ok

2022-05-15 17:46 UTC, merged